#!/usr/bin/env osascript -l JavaScript
// vim: set filetype=javascript:

function CommandRunner(application) {
  var commands = [], results = [];
  var newSession = false;

  this.pipe = function(command) {
    if (newSession) {
      commands = [], results = [];
      newSession = false;
    }

    commands.push(command);
    return this;
  };

  this.getResults = function() {
    return results;
  };

  this.getCommands = function() {
    return commands;
  };

  this.execute = function() {
    commands.forEach(function(command) {
      try {
        result = application.doShellScript(command);
      } catch(e) {
        console.log(e.message);
      } finally {
        results.push(result);
      }
    });

    newSession = true;
    return this;
  };
}

function run(input, parameters) {
  var app = Application.currentApplication();
  app.includeStandardAdditions = true;

  var commandRunner = new CommandRunner(app);
  commandRunner.pipe("defaults read com.apple.finder AppleShowAllFiles").execute();

  var showAllFiles = commandRunner.getResults()[0] === "NO" ? "YES" : "NO";

  commandRunner.pipe("defaults write com.apple.finder AppleShowAllFiles " + showAllFiles);
  commandRunner.pipe("killall -HUP Finder /System/Library/CoreServices/Finder.app");

  commandRunner.execute();

  return input;
}
